apiVersion: v1
kind: Service
metadata:
  name: app-svc-qa
  namespace: qa-viewtask
spec:
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: viewtask-app-qa
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: api-svc-qa
  namespace: qa-viewtask
spec:
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: api-app-qa
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: auth-api-svc-qa
  namespace: qa-viewtask
spec:
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: auth-api-app-qa
  type: ClusterIP
